use_frameworks!

platform :ios, '12.1'

target 'MSRichLinkPreview_Example' do
  pod 'MSRichLinkPreview', :path => '../'
  pod 'Kanna'

  target 'MSRichLinkPreview_Tests' do
    inherit! :search_paths

    
  end
end
